version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 10
    target-branch: "develop"
    labels:
      - "dependencies"
      - "javascript"
      - "automated"
    reviewers:
      - "@repconnect-team"
    assignees:
      - "@repconnect-maintainers"
    commit-message:
      prefix: "chore"
      include: "scope"
    pull-request-branch-name:
      separator: "-"
    rebase-strategy: "auto"
    versioning-strategy: "increase"
    groups:
      # Group all non-major React ecosystem updates
      react-ecosystem:
        patterns:
          - "react*"
          - "@types/react*"
        update-types:
          - "minor"
          - "patch"
      # Group all Material-UI updates
      material-ui:
        patterns:
          - "@mui/*"
          - "@emotion/*"
        update-types:
          - "minor"
          - "patch"
      # Group all testing library updates
      testing:
        patterns:
          - "@testing-library/*"
          - "jest*"
          - "@types/jest"
        update-types:
          - "minor"
          - "patch"
      # Group all build tool updates
      build-tools:
        patterns:
          - "webpack*"
          - "babel*"
          - "eslint*"
          - "prettier*"
          - "typescript"
        update-types:
          - "minor"
          - "patch"
    ignore:
      # Don't update packages that might break
      - dependency-name: "react-scripts"
        update-types: ["version-update:semver-major"]
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]
        
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 5
    target-branch: "develop"
    labels:
      - "dependencies"
      - "github-actions"
      - "automated"
    commit-message:
      prefix: "ci"
      include: "scope"
    pull-request-branch-name:
      separator: "-"