# Netlify configuration
# No functions needed - all API calls go directly to osbackend

[build]
  command = "CI=false GENERATE_SOURCEMAP=false ESLINT_NO_DEV_ERRORS=true npm run build"
  publish = "build"

# Redirect all client-side routes to index.html for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200