# Netlify configuration
# No functions needed - all API calls go directly to osbackend

[build]
  command = "CI=false GENERATE_SOURCEMAP=false ESLINT_NO_DEV_ERRORS=true npm run build"
  publish = "build"

[build.environment]
  # Disable secrets scanning since these environment variables are expected
  # to be in the build output for client-side usage
  SECRETS_SCAN_ENABLED = "false"

# CRITICAL: Serve our auth handler BEFORE React loads
[[redirects]]
  from = "/auth/callback"
  to = "/auth-callback-handler.html"
  status = 200
  force = true  # This ensures it takes precedence

# Redirect all other client-side routes to index.html for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200