name: CI

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ develop ]

permissions:
  contents: read

jobs:
  lint:
    name: CI Check
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Basic CI check
      run: |
        echo "✅ CI check passed"
        echo "Event: ${{ github.event_name }}"
        echo "Actor: ${{ github.actor }}"
        exit 0