name: Dependency Updates

on:
  schedule:
    - cron: '0 3 * * 1'  # Weekly on Monday at 3 AM UTC
  workflow_dispatch:

jobs:
  update-dependencies:
    name: Update NPM Dependencies
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'
        
    - name: Update dependencies
      run: |
        # Update all dependencies to latest minor/patch versions
        npx npm-check-updates -u --target minor
        npm install
        npm audit fix --force || true
        
    - name: Run tests
      run: |
        npm test -- --watchAll=false
        npm run build
      env:
        CI: true
      continue-on-error: true
      
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update npm dependencies'
        title: 'Automated Dependency Updates'
        body: |
          ## Automated Dependency Updates
          
          This PR contains automated dependency updates generated by the weekly dependency update workflow.
          
          ### Changes
          - Updated npm dependencies to their latest minor/patch versions
          - Ran `npm audit fix` to address any security vulnerabilities
          
          ### Checklist
          - [ ] Tests are passing
          - [ ] Build completes successfully
          - [ ] No breaking changes identified
          - [ ] Security vulnerabilities addressed
          
          Please review the changes and test locally before merging.
        branch: deps/automated-updates
        delete-branch: true
        labels: |
          dependencies
          automated
          
  check-outdated:
    name: Check Outdated Dependencies
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Check for outdated packages
      run: |
        echo "## Outdated Dependencies Report" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
        npm outdated || true >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
        
    - name: Check for security vulnerabilities
      run: |
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "## Security Audit Report" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
        npm audit || true >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY